export enum ApiRequestStatus {
  NONE = 'NONE',
  IN_PROGRESS = 'IN_PROGRESS',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum HttpCodes {
  REFRESH_TOKEN_ERROR = 400,
  INVALID_TOKEN = 401,
  FORBIDDEN = 403,
  INTERNAL_SERVER_ERROR = 500,
  CONTENT_UNAVAILABLE = 404,
}

export enum DeviceOrientationTypes {
  'PORTRAIT' = 'PORTRAIT',
  'PORTRAIT-UPSIDEDOWN' = 'PORTRAIT-UPSIDEDOWN',
  'LANDSCAPE-LEFT' = 'LANDSCAPE-LEFT',
  'LANDSCAPE-RIGHT' = 'LANDSCAPE-RIGHT',
  'FACE-UP' = 'FACE-UP',
  'FACE-DOWN' = 'FACE-DOWN',
  'UNKNOWN' = 'UNKNOWN',
}
